Description: >

    This template deploys a VPC, with a pair of public and private subnets spread
    across two Availabilty Zones. It deploys an Internet Gateway, with a default
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
    and default routes for them in the private subnets.

    It is intended for use as a traceme secondary data center required for
    geographic redundancy.

    It is based on a reference architecture created by awslabs
    https://github.com/awslabs/ecs-refarch-cloudformation

Parameters:

    SshKey:
        Type: AWS::EC2::KeyPair::KeyName
        Description: Provide an SSH KeyName to allow SSH access to the instances via a Bastion Host

    VpcClassB:
        Type: Number
        Description: Class B of VPC (10.XXX.0.0/16)
        ConstraintDescription: 'Must be in the range [0-255]'
        MinValue: 0
        MaxValue: 255

    OfficeCidr:
        Type: String
        Description: CIDR of office. Used for various access.
        Default: 209.119.204.118/32
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

    VpnCidr:
        Type: String
        Description: CIDR of VPN. Used for various access.
        Default: 54.190.20.139/32
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
          - Label: VPC
            Parameters:
              - VpcClassB
        ParameterLabels:
            VpcClassB:
                default: Class B of desired VPC
            SshKey:
                default: SSH KeyPair KeyName
            OfficeCidr:
                default: CIDR range of office
            VpnCidr:
                default: CIDR range of vpn
Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 'https://s3.amazonaws.com/codepipeline.traceme.com/${AWS::StackName}/infrastructure/stacks/vpc.yaml'
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            !Sub '10.${VpcClassB}.0.0/16'
                PublicSubnet1CIDR:  !Sub '10.${VpcClassB}.8.0/21'
                PublicSubnet2CIDR:  !Sub '10.${VpcClassB}.16.0/21'
                PrivateSubnet1CIDR: !Sub '10.${VpcClassB}.24.0/21'
                PrivateSubnet2CIDR: !Sub '10.${VpcClassB}.32.0/21'

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 'https://s3.amazonaws.com/codepipeline.traceme.com/${AWS::StackName}/infrastructure/stacks/secondary-security-groups.yaml'
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                OfficeCidr: !Ref OfficeCidr
                VpnCidr: !Ref VpnCidr
