[
    { "ParameterKey": "SshKey", "ParameterValue": "production" },
    { "ParameterKey": "VpcClassB", "ParameterValue": "2" },
    { "ParameterKey": "EcsInstanceType", "ParameterValue": "t2.medium" },
    { "ParameterKey": "EcsClusterSize", "ParameterValue": "2" },
    { "ParameterKey": "WebsiteServiceCount", "ParameterValue": "2" },
    { "ParameterKey": "ProductServiceCount", "ParameterValue": "2" },
    { "ParameterKey": "DatabaseAdminUsername", "ParameterValue": "tracemeprodroot" },
    { "ParameterKey": "DatabaseAdminPassword", "ParameterValue": "d4da6Uf@drUHucEbRuspe7$uVad7XA
      " },
    { "ParameterKey": "DatabaseInstanceType", "ParameterValue": "db.m4.2xlarge" },
    { "ParameterKey": "DatabaseStorageSizeGigabytes", "ParameterValue": "100" }

]
