Description: >
    This template deploys a multi-AZ postgres database

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  DatabaseName:
    Description: The name of the database
    Type: String
    MinLength: 1
    MaxLength: 8
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >
      must begin with a letter and contain only alphanumeric characters.

  AdminUsername:
    NoEcho: true
    Description: The database admin account username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >
      must begin with a letter and contain only alphanumeric characters.

  AdminPassword:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 8

  InstanceType:
    Description: Database instance class
    Type: String
    AllowedValues:
      - db.t2.micro
      - db.m1.small
      - db.m1.large
      - db.m1.xlarge
      - db.m2.xlarge
    ConstraintDescription: >
      must select a valid database instance type.

  StorageSizeGigabytes:
    Description: The size of the database (Gb)
    Type: Number
    MinValue: 5
    MaxValue: 6144
    ConstraintDescription: must be between 5+

  Subnets:
    Description: >
        Choose which subnets the Database should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: >
        Choose which security groups should be applied to the Database
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet
      SubnetIds: !Ref Subnets

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DatabaseName
      AllocatedStorage: !Ref StorageSizeGigabytes
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: !Sub ${EnvironmentName}-rds-pg

      Engine: postgres
      EngineVersion: 9.6
      MultiAZ: true
      MasterUsername: !Ref AdminUsername
      MasterUserPassword: !Ref AdminPassword
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroup
    DeletionPolicy: Snapshot

Outputs:

  DatabaseAddress:
    Description: Postgres database address
    Value: !GetAtt [DatabaseInstance, Endpoint.Address]

  DatabasePort:
    Description: Postgres database port
    Value: !GetAtt [DatabaseInstance, Endpoint.Port]

  DatabaseName:
    Description: Postgres database port
    Value: !Ref DatabaseName
